name: My-Obfuscator
title: My-Obfuscator
description: My JavaScript Obfuscator and Packer
version: 1.12.0
author: Dev Chandel
author_email: dev@gmail.com
url: https://goojdex.github.io
baseurl: /My-Obfuscator
repository: GoojDex/My-Obfuscator
license: MIT

theme: jekyll-theme-hacker
show_downloads: false
google_analytics: UA-0000-1
sass:
  style: compressed

exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    
   
  ]
incremental: false

environment: production
